###
# Auth

POST {{baseUrl}}/users/sign?fields=*
Content-Type: application/json

{
  "login": "test",
  "password": "123456"
}

###
# GET by id

GET {{baseUrl}}users/5f00316d96fcf50daea7ff61?fields=_id,email,profile(*)
X-Token:{{tokenAdmin}}
Content-Type: application/json

###
# Change password

PUT {{baseUrl}}users/5f00316d96fcf50daea7ff61/password
X-Token:{{tokenAdmin}}
Content-Type: application/json

{
  "oldPassword":"123456",
  "newPassword":"1234567"
}

###
# Create or register new user

POST {{baseUrl}}/users?fields=order
Content-Type: application/json

{
  "email": "peter@example.com",
  "username": "peter",
  "password": "123456",
  "profile": {
    "name": "Peter",
    "surname": "Falcon"
  }
}

###
# GET current

GET {{baseUrl}}/users/self?fields=*
Content-Type: application/json
X-Token: {{tokenAdmin}}

###
# Logout

DELETE {{baseUrl}}/users/sign
Content-Type: application/json
X-Token: {{tokenAdmin}}

###
